# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Elm checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13
      uses: actions/setup-node@v1
      with:
        node-version: 13
    - run: npm install
    - name: elm-test
      run: npx --no-install elm-test

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13
      uses: actions/setup-node@v1
      with:
        node-version: 13
    - run: npm install
    - name: elm-format
      run: npx --no-install elm-format --validate
    - name: Build elm docs
      run: ./node_modules/.bin/elm make --docs docs.json
    - uses: dillonkearns/elm-actions@master

  validate-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13
      uses: actions/setup-node@v1
      with:
        node-version: 13
    - run: npm install
    - name: Build elm docs
      run: ./node_modules/.bin/elm make --docs docs.json
    - uses: dillonkearns/elm-actions@master
